# Generated by Django 3.0.2 on 2020-02-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='in_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='out_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='time_outside_office',
            field=models.IntegerField(blank=True),
        ),
    ]
